dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cd 01
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T lab1-0.0.1-Linux.deb -ugulalexan:697b3852c44deb138382fa89c349ba78d6a1af67 "https://api.bintray.com/content/gulalexan/labs_cpp/lab1/1/lab1-0.0.1-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"